insert into public.platforms (name, slug, category, api_enabled, oauth_enabled, publish_enabled, upload_enabled, supports_image, supports_video, supports_article, supports_link, supports_hashtag, supports_tags, supports_analytics, status)
select name, slug, category, api_enabled, oauth_enabled, publish_enabled, upload_enabled, supports_image, supports_video, supports_article, supports_link, supports_hashtag, supports_tags, supports_analytics, status
from (values
  ('Pinterest','pinterest','social',false,false,false,true,true,true,false,true,true,true,false,'manual'),
  ('Medium','medium','blog_publishing',false,false,false,false,false,false,true,true,false,false,false,'manual'),
  ('Imgbox','imgbox','image_hosting',false,false,false,true,true,false,false,false,false,false,false,'manual'),
  ('Publitio','publitio','cloud_storage',false,false,false,false,true,true,false,false,false,false,false,'unsupported'),
  ('Postimages','postimages','image_hosting',false,false,false,true,true,false,false,false,false,false,false,'manual'),
  ('Prnt.sc','prnt-sc','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('Blogger','blogger','blog_publishing',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('FreeImage.host','freeimage-host','image_hosting',false,false,false,true,true,false,false,false,false,false,false,'manual'),
  ('ImgBB','imgbb','image_hosting',false,false,false,true,true,false,false,false,false,false,false,'manual'),
  ('ImageShack','imageshack','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('MediaFire','mediafire','cloud_storage',false,false,false,false,true,true,false,false,false,false,false,'manual'),
  ('Tumblr','tumblr','social',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('Flipboard','flipboard','blog_publishing',false,false,false,false,false,false,true,true,false,false,false,'manual'),
  ('500px','500px','portfolio',false,false,false,false,true,false,false,false,true,true,true,'manual'),
  ('Dropmark','dropmark','cloud_storage',false,false,false,false,true,true,false,false,false,false,false,'unsupported'),
  ('Behance','behance','portfolio',false,false,false,false,true,true,false,true,true,true,false,'manual'),
  ('4shared','4shared','cloud_storage',false,false,false,false,true,true,false,false,false,false,false,'unsupported'),
  ('FlipHTML5','fliphtml5','blog_publishing',false,false,false,false,false,false,true,true,false,false,false,'manual'),
  ('ImageBam','imagebam','image_hosting',false,false,false,true,true,false,false,false,false,false,false,'manual'),
  ('Shutterfly','shutterfly','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('TinyPic.host','tinypic-host','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('pCloud','pcloud','cloud_storage',false,false,false,false,true,true,false,false,false,false,false,'unsupported'),
  ('Instagram','instagram','social',false,false,false,false,true,true,false,true,true,true,false,'unsupported'),
  ('LiveJournal','livejournal','blog_publishing',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('Gifyu','gifyu','image_hosting',false,false,false,true,true,true,false,false,false,false,false,'manual'),
  ('Imgur','imgur','image_hosting',false,false,false,true,true,true,false,true,true,true,false,'manual'),
  ('Google Photos','google-photos','cloud_storage',false,false,false,false,true,true,false,false,false,false,false,'unsupported'),
  ('Facebook','facebook','social',false,false,false,false,true,true,false,true,true,true,false,'unsupported'),
  ('Minds','minds','social',false,false,false,false,true,true,false,true,true,true,false,'unsupported'),
  ('Locanto','locanto','other',false,false,false,false,true,false,false,true,false,false,false,'unsupported'),
  ('X/Twitter','x-twitter','social',false,false,false,false,true,true,false,true,true,true,false,'unsupported'),
  ('Wattpad','wattpad','blog_publishing',false,false,false,false,false,false,true,true,false,false,false,'manual'),
  ('Wix','wix','blog_publishing',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('Penzu','penzu','blog_publishing',false,false,false,false,false,false,true,true,false,false,false,'manual'),
  ('Weebly','weebly','blog_publishing',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('Ghost','ghost','blog_publishing',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('Klook','klook','other',false,false,false,false,true,false,false,true,false,false,false,'unsupported'),
  ('Glints','glints','other',false,false,false,false,true,false,false,true,false,false,false,'unsupported'),
  ('Tripadvisor','tripadvisor','social',false,false,false,false,true,false,false,true,false,false,false,'unsupported'),
  ('Squarespace','squarespace','blog_publishing',false,false,false,false,true,true,true,true,true,true,false,'manual'),
  ('Pixabay','pixabay','image_hosting',false,false,false,false,true,false,false,false,true,true,true,'unsupported'),
  ('Unsplash','unsplash','image_hosting',false,false,false,false,true,false,false,false,true,true,true,'unsupported'),
  ('Pexels','pexels','image_hosting',false,false,false,false,true,false,false,false,true,true,true,'unsupported'),
  ('Reshot','reshot','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('Shopify Stock Photos','shopify-stock-photos','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('Pikwizard','pikwizard','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('Gratisography','gratisography','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('StockVault','stockvault','image_hosting',false,false,false,false,true,false,false,false,false,false,false,'unsupported'),
  ('ImgPile','imgpile','image_hosting',false,false,false,true,true,false,false,false,false,false,false,'manual'),
  ('DeviantArt','deviantart','portfolio',false,false,false,false,true,true,false,true,true,true,false,'manual')
) as seed(name,slug,category,api_enabled,oauth_enabled,publish_enabled,upload_enabled,supports_image,supports_video,supports_article,supports_link,supports_hashtag,supports_tags,supports_analytics,status)
where not exists (select 1 from public.platforms p where p.slug = seed.slug);
